
version: '3.8'

services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter
    command:
      - '--path.rootfs=/host'
    #network_mode: host
    #pid: host
    networks:
      - dyson-spere
    ports:
      - 9100:9100 
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
networks:
  dyson-spere:
    external: true
    name: docker_dyson-spere
